### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by CVXSL** [7lun/DM#2]
I just want to contact you because it has been a while since we have talked and you were the one that got me into making discord bots (with this repository) in august of 2020. 

You might remember Wampus Developer Group and also possibly Bendy Development.

My old names are jinxy and Jinx-_-GT

If you are ok with contacting me, you can by adding me on my new discord account: CVXSL#3291

**Comment by 7lun** [comment]
I remember you and sure 👍
